blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blogwall', views.post_list, name='post_list'),
    path('add_blog/',views.temp, name='create_blog'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.user_login, name='login'),
    path('dashboard/',views.user_dashboard, name='dashboard'),
    path('logout/',views.user_logout, name='logout'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('achieviement/',views.achievement_log, name='achieve'),
    ]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('polls/',include('polls.urls')),
    ]

polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('createpoll/', views.poll,name='createpoll')
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    imag=models.ImageField(upload_to="images/")
    assigned_to = models.CharField(max_length=200)
    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=10) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from .models import Question,Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .form import QuestionForm,ChoiceForm
from django.forms import modelformset_factory

class IndexView(generic.ListView):
    template_name = 'polls/poll_wall.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
def vote(request, question_id):
    print(question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def poll(request):
    if request.session.has_key('_auth_user_id'):
        username=request.user
        choices_formset = modelformset_factory(Choice, form=ChoiceForm, fields=('choice_text',), extra=4)
        if request.method == "POST":
            form=QuestionForm(request.POST,request.FILES)
            choice=choices_formset(request.POST)
            print("hey")
            if form.is_valid() and choice.is_valid():
                post = form.save(commit=False)
                post.pub_date = timezone.now()
                post.assing_to=request.user
                post.save()
                print("well")
                for form in choice:
                    option= form.save(commit=False)
                    option.question = post
                    option.save()
                return redirect('../')
        else:
            form=QuestionForm()
            choice=choices_formset(queryset=Choice.objects.none(),)
        return render(request, 'polls/form.html',{'form': form,'choice':choice,"username":username})
    else:
        return redirect("../login/")

polls/templates/polls/form.html
{% load static%}
<html>
    <head>
        <title>{{username}}|| Polls!!</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Galada&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link href="{% static 'css/readmore.css' %}" rel="stylesheet">
      </head>
    <body>
        <nav class="navbar navbar-light bg-light fixed-top mb-5">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <h1 class="d-flex justify-content-center" style="font-family: 'Galada', cursive; margin-bottom: 0%;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreunion</h1>
              <a class="navbar-brand" style="font-family: 'Caveat', cursive;" href="#">Create Your Blog</a>
              <div class="offcanvas offcanvas-start" style="width: 300px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header pb-0 justify-content-center">
                  <h5 class="offcanvas-title fs-2 pb-0" id="offcanvasNavbarLabel" style="font-family: 'Galada', cursive; padding-bottom: 0px; text-align: center;"><img src="{%static 'logo_svg.png' %}" height="100" width="100"></h5>
                </div>
                <div class="offcanvas-header pt-0 justify-content-center">
                  <div class="row">
                  <h5 class="offcanvas-title fs-5" id="offcanvasNavbarLabel">{{username}}</h5>
                  </div>
                </div>
                <hr class="mb-0" size="10"/>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:dashboard' %}">DashBoard</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:post_list' %}">Blog Wall</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Poll Wall</a>
                      </li>
                      <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:create_blog' %}">Add Blog</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'polls:createpoll' %}">Add Poll</a>
                      </li>
                      <hr class=""/>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:achieve' %}">Add Achievement</a>
                </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                      </li>
                    <hr class=""/>
                </div>
              </div>
            </div>
          </nav>
          <div class="formimg">
          <div class="h-100 d-flex justify-content-center align-items-center">
            <div class="card" style="width: 55rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center fs-2" style="font-family: 'Galada', cursive;">New Blog</h5>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                  <div class="row g-2">
                    <div class="col-md">
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" name="question_text" maxlength="200" required="" id="id_question_text">
                  <label for="floatingInput" style="font-family: 'Caveat', cursive;" class="fs-5">Poll Question</label>
                </div>
                </div>
                <div class="col-md">                  
                  <input type="file" class="form-control form-control-lg" name="imag" accept="image/*" required="" id="id_imag">
                </div>
                </div>
                <input type="hidden" name="form-TOTAL_FORMS" value="4" id="id_form-TOTAL_FORMS">
                <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
                <input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS">
                <input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
                <div class="row g-2">
                  <div class="col-md">
              <div class="form-floating mb-3">
                <input type="text" class="form-control" name="form-0-choice_text" maxlength="200" required="" id="id_form-0-choice_text">
                <label for="id_form-0-choice_text" style="font-family: 'Caveat', cursive;" class="fs-5">Option A</label>
                <input type="hidden" name="form-0-id" id="id_form-0-id">
              </div>
              </div>
              <div class="col-md">                  
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" name="form-1-choice_text" maxlength="200" required="" id="id_form-1-choice_text">
                  <label for="id_form-1-choice_text" style="font-family: 'Caveat', cursive;" class="fs-5">Option B</label>
                  <input type="hidden" name="form-1-id" id="id_form-1-id">
                </div>
              </div>
              </div>
              <div class="row g-2">
                <div class="col-md">
            <div class="form-floating mb-3">
              <input type="text" class="form-control" name="form-2-choice_text" maxlength="200" required="" id="id_form-2-choice_text">
              <label for="id_form-2-choice_text" style="font-family: 'Caveat', cursive;" class="fs-5">Option C</label>
              <input type="hidden" name="form-2-id" id="id_form-2-id">
            </div>
            </div>
            <div class="col-md">                  
              <div class="form-floating mb-3">
                <input type="text" class="form-control" name="form-3-choice_text" maxlength="200" required="" id="id_form-3-choice_text">
                <label for="floatingInput" style="font-family: 'Caveat', cursive;" class="fs-5">Option B</label>
                <input type="hidden" name="form-3-id" id="id_form-3-id">
              </div>
            </div>
            </div>
                <div class="d-grid gap-1 col-6 mx-auto">
                  <button class="btn btn-Info" type="submit">Submit</button>
                </div>
                </form>
              </div>
            </div>
          </div>
          <footer class="footer mt-auto py-1 bg-transparent fixed-bottom">
            <div class="footer">
              <span class="text-bold"><p class="text-center text-bold">Created with ❤ by Rishav_a2z</p></span>
            </div>
          </footer>
          </div>
    </body>
</html>

polls/templates/polls/poll_wall.html
{% load static%}
<html>
    <head>
        <title>Polls List!!</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Galada&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link href="{% static 'css/readmore.css' %}" rel="stylesheet">
        <style>
            a{
                text-decoration: none;
                color: #000000;
                font-family: 'Galada', cursive;
            }
            a:hover {
            text-decoration: underline;
            color: #000000;
            }
        </style>
    </head>
    <body class="">
        <nav class="navbar navbar-light bg-light fixed-top">
            <div class="container-fluid mb-0">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <h1 class="d-flex justify-content-center" style="font-family: 'Galada', cursive; margin-bottom: 0%;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreunion</h1>
                  <a class="navbar-brand" style="font-family: 'Caveat', cursive;" href="#">Create Your Poll</a>
              <div class="offcanvas offcanvas-start" style="width: 300px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title fs-3" id="offcanvasNavbarLabel" style="font-family: 'Galada', cursive;"><img src="{%static 'logo.png' %}" height="50" width="50">reunion</h5>
                  <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <hr class="mb-0" size="10"/>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:post_list' %}">Blog Wall</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'polls:index' %}">Poll Wall</a>
                      </li>
                      <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:create_blog' %}">Add Blog</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:createpoll' %}">Add Poll</a>
                      </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:login' %}">Signin</a>
                      </li>
                    <hr class=""/>
                </div>
              </div>
            </div>
          </nav>
          <div class="d-flex justify-content-center align-items-center pt-5">
            <div class="card pt-5 " style="width: 70%; border: 0;">
                <div class="row row-cols-1 row-cols-md-3 g-4" style="width: 100%">
                    {% for question in latest_question_list %}
                    <div class="col mb-3 pl-2">
                      <div class="card h-100 border border-light shadow-0 cdbg">
                        <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                            <a href="">
                            <img src="../../../media/{{ question.imag }}" class="img-fluid"/>
                              
                            </a>
                          </div>
                        <div class="card-body">
                            <div><a href="" name='blogid' class="">
                          <h5 class="card-title">{{ question.question_text }}</h5></a></div>
                        </div>
                        <form action="{% url 'polls:vote' question.id %}" method="post">
                            {% csrf_token %}
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                        <div class="card-footer">
                            <small class="text-bold" style="font-family: 'Galada', cursive;"><input type="hidden" name="id" id="id" value="{{ choice.id }}">
                                <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                                <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label></small>
                        </div>
                        {% endfor %}
                        <div class="card-footer">
                            <small class="text-bold" style="font-family: 'Galada', cursive;"><div class="d-grid gap-1 col-6 mx-auto">
                                <button class="btn btn-Info" type="submit">Submit</button>
                              </div></small>
                        </div>
                        </form>
                        <div class="card-footer">
                           <small class="text-muted" style="font-family: 'caveat', cursive;">{{ question.pub_date}}</small>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
          </div>
          <footer class="footer mt-auto py-3 bg-light">
            <div class="footer">
              <span class="text-muted "><p class="text-center">Created with ❤ by Rishav_a2z</p></span>
            </div>
          </footer>
    </body>
</html>

polls/templates/polls/results.html
{% load static%}
<html>
    <head>
        <title>Poll Result!!</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Galada&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link href="{% static 'css/readmore.css' %}" rel="stylesheet">
      </head>
    <body>
        <nav class="navbar navbar-light bg-light fixed-top mb-5">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <h1 class="d-flex justify-content-center" style="font-family: 'Galada', cursive; margin-bottom: 0%;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreunion</h1>
              <a class="navbar-brand" style="font-family: 'Caveat', cursive;" href="#">Create Your Blog</a>
              <div class="offcanvas offcanvas-start" style="width: 300px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title fs-3" id="offcanvasNavbarLabel" style="font-family: 'Galada', cursive;"><img src="{%static 'logo.png' %}" height="50" width="50">reunion</h5>
                  <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <hr class="mb-0" size="10"/>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link active" href="{% url 'blog:post_list' %}">Blog Wall</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Poll Wall</a>
                      </li>
                      <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:create_blog' %}">Add Blog</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:createpoll' %}">Add Poll</a>
                      </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:login' %}">Signin</a>
                      </li>
                    <hr class=""/>
                </div>
              </div>
            </div>
          </nav>
          <div class="formimg">
          <div class="h-100 d-flex justify-content-center align-items-center">
            <div class="card" style="width: 30%;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center fs-2" style="font-family: 'caveat', cursive;">Polls</h5>
                <center><hr style="width:30%; " size="6"/></center>
                <h1 class="fs-3" style="font-family: 'Galada'">{{ question.question_text }}</h1>
                <hr/>
                <ul>
                    {% for choice in question.choice_set.all %}
                        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                    {% endfor %}
                    </ul>
                    
                    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
              </div>
            </div>
          </div>
          <footer class="footer mt-auto py-1 bg-transparent fixed-bottom">
            <div class="footer">
              <span class="text-bold"><p class="text-center text-bold">Created with ❤ by Rishav_a2z</p></span>
            </div>
          </footer>
          </div>
    </body>
</html>