blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blogwall', views.post_list, name='post_list'),
    path('add_blog/',views.temp, name='create_blog'),
    path('signup/',views.signup, name='signup'),
    path('login/',views.user_login, name='login'),
    path('dashboard/',views.user_dashboard, name='dashboard'),
    path('logout/',views.user_logout, name='logout'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('achieviement/',views.achievement_log, name='achieve'),
    ]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('polls/',include('polls.urls')),
    ]

polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('createpoll/', views.poll,name='createpoll')
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from distutils.command.upload import upload
import email
from email import message
from pyexpat import model
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.validators import RegexValidator

class Post(models.Model):
    author= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    imag=models.ImageField(upload_to="images/")
    title = models.CharField(max_length=150)
    subtitle=models.CharField(max_length=300)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Signup(models.Model):
    username=models.CharField(max_length=15,primary_key=True)
    email=models.EmailField(max_length=50)
    password=models.CharField(max_length=30)
    cpassword=models.CharField(max_length=30)
    def __str__(self):
        return self.username

class Achivement(models.Model):
    date=models.DateField()
    text=models.CharField(max_length=300)

class Contact(models.Model):
    name=models.CharField(max_length=200)
    email=models.EmailField(max_length=50, primary_key=True)
    subject=models.CharField(max_length=400)
    message=models.TextField()

blog/forms.py
import imp
from operator import mod
from django import forms

from .models import Post
from .models import Achivement
from .models import Contact

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','imag','subtitle', 'text')

class AchivementForm(forms.ModelForm):
    class Meta:
        model = Achivement
        fields=("date","text")

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields=("name","email",'subject','message')

blog/views.py
from django.shortcuts import render
from .models import Achivement, Post
from polls.models import Question,Choice
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from .forms import AchivementForm
from .signup import SignupForm
from .forms import ContactForm
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

def index(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:3]
    question=Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:3]
    achievements=Achivement.objects.order_by("-date")
    if request.method == "POST":
            form = ContactForm(request.POST)
            if form.is_valid():
                log = form.save(commit=False)
                log.save()
                return redirect('/')
    else:
        form = ContactForm()
    return render(request, 'blog/index.html',{'latest_question_list':question,'posts':posts,'achievements':achievements})

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            if post.password==post.cpassword:
                user = User.objects.create_user(post.username, post.email, post.password)
                user.save()
                return redirect("../login")
    else:
        form = SignupForm()
    return render(request, 'blog/signup.html',{'form': form})

def user_login(request):
    print(request.method)
    if request.session.has_key('_auth_user_id'):
        return redirect("../dashboard/")
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            print("su")
            if user is not None:
                login(request, user)
                print("hiuh")
                return redirect("../dashboard/")
            else:
                message="Wrong username and Password"
                return render(request, 'blog/login.html',{"message":message})
        return render(request, 'blog/login.html')

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/wall.html', {'posts': posts})
        
def user_dashboard(request):
    print(request.session.keys())
    if request.session.has_key('_auth_user_id'):
        username=request.user
        posts = Post.objects.filter(published_date__lte=timezone.now(), author=username).order_by('published_date')
        return render(request, 'blog/dashboard_profile.html', {'posts': posts,"username":username})
    else:
        return redirect("../login/")

def user_logout(request):
    request.session.flush()
    return redirect("/")

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def temp(request):
    if request.session.has_key('_auth_user_id'):
        username=request.user
        if request.method == "POST":
            form = PostForm(request.POST,request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.published_date = timezone.now()
                post.save()
                print(post.author)
                return redirect('/')
        else:
            form = PostForm()
        return render(request, 'blog/form.html', {'form': form,"username":username})
    else:
        return redirect("../login/")

def achievement_log(request):
    if request.session.has_key('_auth_user_id'):
        username=request.user
        if request.method == "POST":
            form = AchivementForm(request.POST)
            if form.is_valid():
                log = form.save(commit=False)
                log.save()
                return redirect('/')
        else:
            form = AchivementForm()
        return render(request, 'blog/achievement.html', {'form': form,"username":username})
    else:
        return redirect("../login/")


blog/templates/blog/achievement.html
{% load static%}
<html>
    <head>
        <title>{{username}}|Pride!!</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Galada&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link href="{% static 'css/read.css' %}" rel="stylesheet">
      </head>
    <body>
        <nav class="navbar navbar-light bg-light fixed-top mb-5">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <h1 class="d-flex justify-content-center" style="font-family: 'Galada', cursive; margin-bottom: 0%;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreunion</h1>
              <a class="navbar-brand" style="font-family: 'Caveat', cursive;" href="#">Rishav Kumar</a>
              <div class="offcanvas offcanvas-start" style="width: 300px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header pb-0 justify-content-center">
                  <h5 class="offcanvas-title fs-2 pb-0" id="offcanvasNavbarLabel" style="font-family: 'Galada', cursive; padding-bottom: 0px; text-align: center;"><img src="{%static 'logo_svg.png' %}" height="100" width="100"></h5>
                </div>
                <div class="offcanvas-header pt-0 justify-content-center">
                  <div class="row">
                  <h5 class="offcanvas-title fs-5" id="offcanvasNavbarLabel">{{username}}</h5>
                  </div>
                </div>
                <hr class="mb-0" size="10"/>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:dashboard' %}">DashBoard</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:post_list' %}">Blog Wall</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Poll Wall</a>
                      </li>
                      <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link active" href="{% url 'blog:create_blog' %}">Add Blog</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:createpoll' %}">Add Poll</a>
                      </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                      </li>
                    <hr class=""/>
                </div>
              </div>
            </div>
          </nav>
          <div class="formimg">
          <div class="h-100 d-flex justify-content-center align-items-center">
            <div class="card" style="width: 45rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center fs-2" style="font-family: 'Galada', cursive;">New Achievements</h5>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                  <div class="row g-2">
                    <div class="col-md">
                <div class="form-floating mb-3">
                  <input type="date" class="form-control" name="date" required="" id="id_date" placeholder="">
                  <label for="floatingInput" style="font-family: 'Caveat', cursive;" class="fs-5">Enter Date</label>
                </div>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" name="text" maxlength="300" required="" id="id_text">
                    <label for="floatingSubtitle" style="font-family: 'Caveat', cursive;" class="fs-5">Enter Achievement</label>
                </div>
                <div class="d-grid gap-1 col-6 mx-auto">
                  <button class="btn btn-Info" type="submit">Submit</button>
                </div>
                </form>
              </div>
            </div>
          </div>
          <footer class="footer mt-auto py-1 bg-transparent fixed-bottom">
            <div class="footer">
              <span class="text-bold"><p class="text-center text-bold">Created with ❤ by Rishav_a2z</p></span>
            </div>
          </footer>
          </div>
    </body>
</html>

blog/templates/blog/dashboard_profile.html
{% load static%}
<html>
    <head>
        <title>{{username}}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Galada&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link href="{% static 'css/read.css' %}" rel="stylesheet">
        <style>
            a{
                text-decoration: none;
                color: #000000;
                font-family: 'Galada', cursive;
            }
            a:hover {
            text-decoration: underline;
            color: #000000;
            }
        </style>
    </head>
    <body class="">
      <nav class="navbar navbar-light bg-light fixed-top">
        <div class="container-fluid mb-0">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <h1 class="d-flex justify-content-center" style="font-family: 'Galada', cursive; margin-bottom: 0%;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreunion</h1>
              <a class="navbar-brand" style="font-family: 'Caveat', cursive;" href="#">Create Your Blog</a>
          <div class="offcanvas offcanvas-start" style="width: 300px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header pb-0 justify-content-center">
              <h5 class="offcanvas-title fs-2 pb-0" id="offcanvasNavbarLabel" style="font-family: 'Galada', cursive; padding-bottom: 0px; text-align: center;"><img src="{%static 'logo_svg.png' %}" height="100" width="100"></h5>
            </div>
            <div class="offcanvas-header pt-0 justify-content-center">
              <div class="row">
              <h5 class="offcanvas-title fs-5" id="offcanvasNavbarLabel">{{username}}</h5>
              </div>
            </div>
            <hr class="mb-0" size="10"/>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                </li>
                <hr class=""/>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'blog:dashboard' %}">DashBoard</a>
                </li>
                <hr class=""/>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:post_list' %}">Blog Wall</a>
                </li>
                <hr class=""/>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:index' %}">Poll Wall</a>
                  </li>
                  <hr class=""/>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:create_blog' %}">Add Blog</a>
                </li>
                <hr class=""/>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:createpoll' %}">Add Poll</a>
                  </li>
                <hr class=""/>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:achieve' %}">Add Achievement</a>
                </li>
                <hr class=""/>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                  </li>
                <hr class=""/>
                </ul>
            </div>
          </div>
        </div>
      </nav>
          <div class="d-flex justify-content-center align-items-center" style="padding-top: 30px;">
            <div class="card pt-5 " style="width: 70%; border: 0;">
                <div class="row row-cols-1 row-cols-md-3 g-4" style="width: 100%;">
                    {% for post in posts %}
                    <div class="col mb-3 pl-2 pt-0">
                      <div class="card h-100 border border-light shadow-0 cdbg">
                        <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                            <a href="{% url 'blog:post_detail' pk=post.pk %}">
                            <img src="{{ post.imag.url}}" class="img-fluid"/>
                              <div class="mask" style="background-color: rgb(255, 255, 255);"></div>
                            </a>
                          </div>
                        <div class="card-body">
                            <div><a href="{% url 'blog:post_detail' pk=post.pk %}" name='blogid' class="">
                          <h5 class="card-title">{{ post.title }}</h5></a></div>
                          <p class="card-text">
                            {{ post.subtitle }}
                          </p>
                        </div>
                        <div class="card-footer">
                            <small class="text-bold" style="font-family: 'Galada', cursive;">{{ post.author}}</small>
                        </div>
                        <div class="card-footer">
                           <small class="text-muted" style="font-family: 'caveat', cursive;">{{ post.published_date}}</small>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
          </div>
          <footer class="footer mt-auto py-3 bg-light">
            <div class="footer">
              <span class="text-muted "><p class="text-center">Place sticky footer content here.</p></span>
            </div>
          </footer>
    </body>
</html>

blog/templates/blog/form.html
{% load static%}
<html>
    <head>
        <title>{{username}}|Blog!!</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Galada&display=swap" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link href="{% static 'css/read.css' %}" rel="stylesheet">
      </head>
    <body>
        <nav class="navbar navbar-light bg-light fixed-top mb-5">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <h1 class="d-flex justify-content-center" style="font-family: 'Galada', cursive; margin-bottom: 0%;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreunion</h1>
              <a class="navbar-brand" style="font-family: 'Caveat', cursive;" href="#">Create Your Blog</a>
              <div class="offcanvas offcanvas-start" style="width: 300px;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header pb-0 justify-content-center">
                  <h5 class="offcanvas-title fs-2 pb-0" id="offcanvasNavbarLabel" style="font-family: 'Galada', cursive; padding-bottom: 0px; text-align: center;"><img src="{%static 'logo_svg.png' %}" height="100" width="100"></h5>
                </div>
                <div class="offcanvas-header pt-0 justify-content-center">
                  <div class="row">
                  <h5 class="offcanvas-title fs-5" id="offcanvasNavbarLabel">{{username}}</h5>
                  </div>
                </div>
                <hr class="mb-0" size="10"/>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:dashboard' %}">DashBoard</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'blog:post_list' %}">Blog Wall</a>
                    </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:index' %}">Poll Wall</a>
                      </li>
                    <hr class=""/>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:createpoll' %}">Add Poll</a>
                      </li>
                      <hr class=""/>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog:achieve' %}">Add Achievement</a>
                </li>
                    <hr class=""/>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
                      </li>
                    <hr class=""/>
                </div>
              </div>
            </div>
          </nav>
          <div class="formimg">
          <div class="h-100 d-flex justify-content-center align-items-center">
            <div class="card" style="width: 55rem;">
              <div class="card-body">
                <h5 class="card-title d-flex justify-content-center fs-2" style="font-family: 'Galada', cursive;">New Blog</h5>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                  <div class="row g-2">
                    <div class="col-md">
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" name="title" maxlength="150" required="" id="id_title">
                  <label for="floatingInput" style="font-family: 'Caveat', cursive;" class="fs-5">Enter Title</label>
                </div>
                </div>
                <div class="col-md">                  
                  <input type="file" class="form-control form-control-lg" name="imag" accept="image/*" required="" id="id_imag">
                </div>
                </div>
                <div class="form-floating mb-3">
                  <input type="text" class="form-control" name="subtitle" maxlength="300" required="" id="id_subtitle">
                  <label for="floatingSubtitle" style="font-family: 'Caveat', cursive;" class="fs-5">Enter Subtitle</label>
                </div>
                <div class="form-floating mb-3">
                  <textarea class="form-control" name="text" cols="40" rows="4" style="height: 200px" required="" id="id_text"></textarea>
                  <label for="floatingtext" style="font-family: 'Caveat', cursive;" class="fs-4">Blog</label>
                </div>
                <div class="d-grid gap-1 col-6 mx-auto">
                  <button class="btn btn-Info" type="submit">Submit</button>
                </div>
                </form>
              </div>
            </div>
          </div>
          <footer class="footer mt-auto py-1 bg-transparent fixed-bottom">
            <div class="footer">
              <span class="text-bold"><p class="text-center text-bold">Created with ❤ by Rishav_a2z</p></span>
            </div>
          </footer>
          </div>
    </body>
</html>